### ISSUE TITLE
Request: Support diff3 style "base" markers

### ISSUE THREAD

**Issue by cassdeckard** [liying2008/git-conflict#10]
In my `.gitconfig` I like to set `merge.conflictstyle=diff3` ([see docs](https://git-scm.com/docs/merge-config#Documentation/merge-config.txt-mergeconflictStyle)) to help give me additional context when resolving conflicts. This causes an additional section to appear, delimited by a new `|||||||` marker and the regular `=======` marker.

Currently this plugin doesn't notice that section at all and treats it as part of the "Upstream", "HEAD" or "Current" section. This wouldn't be such a big deal, but it makes it so the "Accept Current Changes" and "Accept Both Changes" fix options both incorrectly leave that diff3-enabled "Base" or "Common ancestor" section in with the Upstream/HEAD one.

**Comment by cassdeckard** [comment]
除了这个，这个插件非常有用！ 谢谢你发布它！^ _ ^

**Comment by liying2008** [comment]
Thank you very much for the suggestion, I will modify it to implement this feature. @cassdeckard

**Comment by liying2008** [comment]
A new version v2.0.0 has been released and this feature is supported.
