### ISSUE TITLE
Any reason this wouldn't work on PhpStorm 2020.1.1?

### ISSUE THREAD

**Issue by xmarklar** [liying2008/git-conflict#3]
Can't find by searching plugins Marketplace in PhpStorm.  Download the .jar file from https://plugins.jetbrains.com/plugin/10656-git-conflict  and manually install.  
Looks okay, but if you leave Settings screen and come right back to Settings... **the plugin is gone**.  

What's wrong?  Or, what's needed to get this to work again?  Thanks!

**Comment by liying2008** [comment]
I recompiled and packaged it: https://github.com/liying2008/git-conflict/releases/tag/v1.0.1 .
I have tested this version and it works fine.
